service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: ap-southeast-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: buttery-bot
    handler: lambda.handler
    description: Saga Buttery Bot
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"